main/urls.py
from django.urls import path

from .views import index, DocLoginView, profile, DocLogoutView, ChangeUserInfoView, DocPasswordChangeView
from .views import RegisterDoneView, RegisterUserView, detail, by_priority, profile_doc_detail, profile_doc_add, \
    profile_doc_add1, profile_doc_change, profile_doc_delete

app_name = 'main'
urlpatterns = [
    path('', index, name='index'),
    path('accounts/login/', DocLoginView.as_view(), name='login'),
    path('account/profile/change/<int:pk>', profile_doc_change, name='profile_doc_change'),
    path('account/profile/delete/<int:pk>', profile_doc_delete, name='profile_doc_delete'),
    path('accounts/profile/add', profile_doc_add, name='profile_doc_add'),
    path('accounts/profile/add1', profile_doc_add1, name='profile_doc_add1'),
    path('accounts/profile/<int:pk>/', profile_doc_detail, name='profile_doc_detail'),
    path('accounts/profile/', profile, name='profile'),
    path('account/logout',DocLogoutView.as_view(), name='logout'),
    path('accounts/profile/change/', ChangeUserInfoView.as_view(), name='profile_change'),
    path('accounts/password/change/', DocPasswordChangeView.as_view(), name='password_change'),
    path('accounts/register/done/', RegisterDoneView.as_view(), name='register_done'),
    path('accounts/register/', RegisterUserView.as_view(), name='register'),
    path('<int:status_pk>/<int:pk>/', detail, name='detail'),
    path('<int:pk>/', by_priority, name='by_priority'),
    #path('<str:page>/', other_page, name='other'),
]

rboard/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.contrib.staticfiles.views import serve
from django.views.decorators.cache import never_cache
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls', namespace='')),
]

if settings.DEBUG:
    urlpatterns.append(path('static/<path:path>', never_cache(serve)))
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.db.models.signals import post_save
from .utilities import get_timestamp_path


class AdvUser(AbstractUser):
    send_messages = models.BooleanField(default=True, verbose_name='Слать распознанный текст на почту')

    class Meta(AbstractUser.Meta):
        pass

    def delete(self, *args, **kwargs):
        for doc in self.doc_set_all():
            doc.delete()
        super().delete(*args, **kwargs)

class Priority(models.Model):
    name = models.CharField(max_length=20, db_index=True, verbose_name='Название')

    def __str__(self):
        return self.name

    class Meta:
        verbose_name_plural = 'Приоритеты'
        verbose_name = 'Приоритет'
        ordering = ['name']

class Document(models.Model):
    image = models.ImageField(blank=True, upload_to=get_timestamp_path, verbose_name='Изображение')
    content = models.TextField(verbose_name='Содержание', blank=True)
    title = models.CharField(max_length=20, verbose_name='Название', blank=True)
    published = models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Опубликовано')
    priority = models.ForeignKey(Priority, null=True, on_delete=models.PROTECT, verbose_name='Приоритет')
    author = models.ForeignKey(AdvUser, on_delete=models.CASCADE, verbose_name='Автор')

    class Meta:
        verbose_name_plural='Документы'
        verbose_name='Документ'
        ordering=['-published']





main/forms.py
from django import forms
from django.contrib.auth import password_validation
from django.core.exceptions import ValidationError
from django.forms import inlineformset_factory

from .models import AdvUser, Document

class ChangeUserInfoForm(forms.ModelForm):
    email = forms.EmailField(required=True, label='Адрес электронной почты')

    class Meta:
        model = AdvUser
        fields = ('username', 'email', 'first_name', 'last_name', 'send_messages')

class RegisterUserForm(forms.ModelForm):
    email = forms.EmailField(required=True, label='Адрес электронной почты')
    password1 = forms.CharField(label='Пароль', widget=forms.PasswordInput,
                                help_text=password_validation.password_validators_help_text_html())
    password2 = forms.CharField(label='Пароль (повторно)', widget=forms.PasswordInput,
                                help_text='Введите тот же самый пароль еще раз для проверки')

    def clean_password1(self):
        password1 = self.cleaned_data['password1']
        if password1:
            password_validation.validate_password(password1)
        return password1

    def clean(self):
        super().clean()
        password1 = self.cleaned_data['password1']
        password2 = self.cleaned_data['password2']
        if password1 and password2 and password1 != password2:
            errors = {'password2': ValidationError('Введенные пароли не совпадают', code='password_mismatch')}
            raise ValidationError(errors)

    def save(self, commit=True):
        user = super().save(commit=True)
        user.set_password(self.cleaned_data['password1'])
        if commit:
            user.save()
        return user

    class Meta:
        model = AdvUser
        fields = ('username', 'email', 'password1', 'password2', 'first_name', 'last_name',
                  'send_messages')


class DocumentForm(forms.ModelForm):

    class Meta:
        model = Document
        fields = ('content', 'title', 'priority', 'author', 'priority')
        widgets = {'author': forms.HiddenInput}

class DocumentImageForm(forms.ModelForm):

    class Meta:
        model = Document
        fields = ('content', 'title', 'priority', 'author', 'image')
        widgets = {'author': forms.HiddenInput, 'priority': forms.HiddenInput,  'content': forms.HiddenInput, 'title':forms.HiddenInput}

main/views.py
from django.shortcuts import render
from django.contrib.auth.views import LoginView, LogoutView, PasswordChangeView
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic.edit import UpdateView, CreateView
from django.contrib.messages.views import SuccessMessageMixin
from django.urls import reverse_lazy
from django.shortcuts import get_object_or_404
from django.views.generic.base import TemplateView
from django.core.paginator import Paginator
from django.shortcuts import redirect

from .models import AdvUser, Priority, Document
from .forms import ChangeUserInfoForm,RegisterUserForm, DocumentForm, DocumentImageForm

from PIL import Image
import pytesseract
import cv2

def index(request):
    return render(request, 'main/index.html')

class DocLoginView(LoginView):
    template_name = 'main/login.html'

@login_required
def profile(request):
    docs = Document.objects.filter(author=request.user.pk)
    context = {'docs': docs}
    return render(request, 'main/profile.html', context)

@login_required
def profile_doc_detail(request, pk):
    doc = get_object_or_404(Document, pk=pk)
    context = {'doc': doc}
    return render(request, 'main/profile_doc_detail.html', context)

@login_required
def profile_doc_add(request, image, text):
    if request.method == 'POST':
        form = DocumentForm(request.POST, request.FILES)
        if form.is_valid():
            doc = form.save()
            return redirect('main:profile')
    else:
        image = image
        text = text
        priority = get_object_or_404(Priority, id=2)
        form = DocumentForm(initial={'author': request.user.pk, 'priority' : priority, 'image': image, 'content': content })
    context = {'form': form}
    return render(request, 'main/profile_doc_add.html', context)


@login_required
def profile_doc_add1(request):
    if request.method == 'POST':
        form = DocumentImageForm(request.POST, request.FILES)
        if form.is_valid():
            doc = form.save(commit=False)
            pytesseract.pytesseract.tesseract_cmd = r'C:\Program Files\Tesseract-OCR\tesseract.exe'
            doc.content = pytesseract.image_to_string(Image.open(doc.image), lang='rus')
            doc = form.save()
            doc.save()
            return redirect('main:profile_doc_change', pk=doc.pk)
        else:
            form = DocumentImageForm
    else:
        priority = get_object_or_404(Priority, name="Важное")
        form = DocumentImageForm(initial={'author': request.user.pk, 'priority': priority})
    context = {'form': form}
    return render(request, 'main/profile_doc_add1.html', context)

@login_required
def profile_doc_change(request, pk):
    doc = get_object_or_404(Document, pk=pk)
    if request.method == 'POST':
        form = DocumentForm(request.POST, request.FILES, instance=doc)
        if form.is_valid():
            doc = form.save()
            return redirect('main:profile')
    else:
        form = DocumentForm(instance=doc)
    context = {'form': form}
    return render(request, 'main/profile_doc_change.html', context)

@login_required
def profile_doc_delete(request, pk):
    doc = get_object_or_404(Document, pk=pk)
    if request.method == 'POST':
        doc.delete()
        return redirect('main:profile')
    else:
        context = {'doc': doc}
        return render(request, 'main/profile_doc_delete.html', context)


class DocLogoutView(LoginRequiredMixin, LogoutView):
    template_name = 'main/logout.html'


class ChangeUserInfoView(SuccessMessageMixin, LoginRequiredMixin, UpdateView):
    model = AdvUser
    template_name = 'main/change_user_info.html'
    form_class = ChangeUserInfoForm
    success_url = reverse_lazy('main:profile')
    success_message = 'Личные данные пользователя изменены'

    def dispatch(self, request, *args, **kwargs):
        self.user_id = request.user.pk
        return super().dispatch(request, *args, **kwargs)

    def get_object(self, queryset=None):
        if not queryset:
            queryset = self.get_queryset()
        return get_object_or_404(queryset, pk=self.user_id)

class DocPasswordChangeView(SuccessMessageMixin, LoginRequiredMixin, PasswordChangeView):
    template_name = 'main/password_change.html'
    success_url = reverse_lazy('main:profile')
    success_message = 'Пароль пользователя изменен'

class RegisterUserView(CreateView):
    model = AdvUser
    template_name = 'main/register_user.html'
    form_class = RegisterUserForm
    success_url = reverse_lazy('main:register_done')

class RegisterDoneView(TemplateView):
    template_name = 'main/register_done.html'

def by_priority(request, pk):
    priority = get_object_or_404(Priority, pk=pk)
    docs = Document.objects.filter(priority=pk, author=request.user.pk)
    paginator = Paginator(docs, 2)
    if 'page' in request.GET:
        page_num = request.GET['page']
    else:
        page_num = 1
    page = paginator.get_page(page_num)
    context = {'priority': priority, 'page': page, 'docs': page.object_list}
    return render(request, 'main/by_priority.html', context)

def detail(request, priority_pk, pk):
    doc = get_object_or_404(Document, pk=pk)
    context = {'doc': doc}
    return render(request, 'main/detail.html', context)

main/templates/main/by_priority.html
{% extends "layout/basic.html" %}

{% load thumbnail %}
{% load static %}
{% load bootstrap4 %}

{% block title %}{{ priority }}{% endblock %}

{% block content %}
<h2 class="mb-2">{{ priority }}</h2>
{% if docs %}
<ul class="list-unstyled">
    {% for doc in docs %}
    <li class="media my-5 p-3 border">
        {% url 'main:detail' priority_pk=priority.pk pk=doc.pk as url %}
        <a href="{{ url }}{{ all }}">
        {% if doc.image %}
        <img class="mr-3" src="{% thumbnail doc.image 'default' %}">
        {% else %}
        <img class="additional-image" src="{% static 'main/icon.jpg' %}">
        {% endif %}
        </a>
        <div class="media-body">
          <h3><a href="{{ url }}{{ all }}">{{ doc.title }}</a></h3>
          <div>{{ doc.content }}</div>
          <p class="text-right">{{doc.published}}</p>
        </div>
    </li>
    {% endfor %}
</ul>
{% bootstrap_pagination page  %}
{% endif %}
{% endblock %}

main/templates/main/change_user_info.html
{% extends "layout/basic.html" %}

{% load bootstrap4 %}

{% block title %}Правка личных данных{% endblock %}

{% block content %}
<h2>Правка личных данных пользователя {{ user.username }}</h2>
<form method="post">
    {% csrf_token %}
    {% bootstrap_form form layout='horizontal' %}
    {% buttons submit='Сохранить' %}{% endbuttons %}
</form>
{% endblock %}

main/templates/main/detail.html
{% extends "layout/basic.html" %}

{% load bootstrap4 %}

{% block title %}{{ doc.title }} - {{ doc.priority.name }}{% endblock %}

{% block content %}
<div class="container-fluid mt-3">
    <div class="row">
        {% if doc.image %}
        <div class="col-md-auto"><img src="{{ doc.image.url }}" class="main-image"></div>
        {% endif %}
        <div class="col">
            <h2>{{ doc.title }}</h2>
            <p>{{ doc.content }}</p>
            <p class="text-right font-italic">Документ распознан {{ rb.published }}</p>
        </div>
    </div>
</div>
<p><a href="{% url 'main:by_status' pk=rb.status.pk %}{{ all }}">Назад</a></p>
{% endblock %}

main/templates/main/index.html
{% extends "layout/basic.html" %}

{% block content %}
<h2>Рады приветствовать Вас!</h2>
<p>Для просмотра документов или распознавания текста, пожалуйста, войдите в систему</p>

{% endblock %}

main/templates/main/login.html
{% extends "layout/basic.html" %}

{% load bootstrap4 %}

{% block title %}Вход{% endblock %}

{% block content %}
<h2>Вход</h2>
{% if user.is_authenticated %}
<p>Вы уже выполнили вход.</p>
{% else %}
<form method="post">
    {% csrf_token %}
    {% bootstrap_form form layout='horizontal' %}
    <input type="hidden" name="text" value="{{ next }}">
    {% buttons submit='Войти' %}{% endbuttons %}
</form>
{% endif %}
{% endblock %}


main/templates/main/logout.html
{% extends "layout/basic.html" %}

{% block title %}Выход{% endblock %}

{% block content %}
<h2>Выход</h2>
<p>Вы успешно вышли с сайта.</p>
{% endblock %}

main/templates/main/profile.html
{% extends "layout/basic.html" %}

{% load thumbnail %}
{% load static %}

{% block title %}Профиль пользователя{% endblock %}

{% block content %}
<h2>Профиль пользователя {{ user.username }}</h2>
{% if user.first_name and user.last_name %}
<p>Здравствуйте, {{ user.first_name }} {{ user.last_name }}!</p>
{% else %}
<p>Здравствуйте!</p>
{% endif %}
<p><a href="{% url 'main:profile_doc_add1' %}">Добавить документ картинкой</a></p>
{% if docs %}
<h3>Ваши документы</h3>
<ul class="list-unstyled">
    {% for doc in docs %}
    <li class="media my-5 p-3 border">
        {% url 'main:profile_doc_detail' pk=doc.pk as url %}
        <a href="{{ url }}">
        {% if doc.image %}
        <img class="mr-3" src="{% thumbnail doc.image 'default' %}">
        {% else %}
        <img class="mr-3" src="{% static 'main/empty.jpg' %}">
        {% endif %}
        </a>
        <div class="media-body">
            <h3><a href="{{ url }}">{{ doc.title }}</a></h3>
            <p class="text-right mt-2">
                <a href="{% url 'main:profile_doc_change' pk=doc.pk %}">Исправить</a>
                <a href="{% url 'main:profile_doc_delete' pk=doc.pk %}">Удалить</a>
            </p>
        </div>
    </li>
    {% endfor %}
</ul>
{% endif %}
{% endblock %}

main/templates/main/profile_doc_add.html
{% extends "layout/basic.html" %}

{% load bootstrap4 %}

{% block title %}Добавление ддокумента - Профиль пользователя{% endblock %}

{% block content %}
<h2>Добавление документа</h2>
<form method="post">
    {% csrf_token %}
    {% bootstrap_form form layout='horizontal' %}
    {% buttons submit='Добавить' %}{% endbuttons %}
</form>
{% endblock %}

main/templates/main/profile_doc_add1.html
{% extends "layout/basic.html" %}

{% load bootstrap4 %}

{% block title %}Добавление документа - Профиль пользователя{% endblock %}

{% block content %}
<h2>Добавление документа</h2>
<form method="post" enctype="multipart/form-data" accept="image/*">
    {% csrf_token %}
    {% bootstrap_form form layout='horizontal' %}
    {% buttons submit='Добавить' %}{% endbuttons %}
</form>
{% endblock %}

main/templates/main/profile_doc_change.html
{% extends "layout/basic.html" %}

{% load bootstrap4 %}

{% block title %}Правка документа- Профиль пользователя{% endblock %}

{% block content %}
<h2>Правка документа</h2>
<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {% bootstrap_form form layout='horizontal' %}
    {% buttons submit='Сохранить' %}{% endbuttons %}
</form>
{% endblock %}

main/templates/main/profile_doc_delete.html
{% extends "layout/basic.html" %}

{% block title %}Удаление документа - Профиль пользователя{% endblock %}

{% block content %}
<h2>Удаление документа</h2>
<div class="container-fluid mt-3">
    <div class="row">
        {% if doc.image %}
        <div class="col-md-auto"><img src="{{ doc.image.url }}" class="main-image"></div>
        {% endif %}
        <div class="col">
            <h2>{{ doc.title }}</h2>
            <p>ТЕкст: {{ doc.content }} {{ doc.content }}</p>
            <p class="font-italic">Приоритет: {{ doc.priority }}</p>
            <p class="text-right font-italic">Документ распознан {{ doc.published }}</p>
        </div>
    </div>
</div>
<form method="post">
    {% csrf_token %}
    <input type="submit" value="Удалить">
</form>
{% endblock %}

main/templates/main/profile_doc_detail.html
{% extends "layout/basic.html" %}

{% block title %}{{ bb.title }} - Профиль пользователя{% endblock %}

{% block content %}
<div class="container-fluid mt-3">
    <div class="row">
        {% if doc.image %}
        <div class="col-md-auto"><img src="{{ doc.image.url }}" class="main-image"></div>
        {% endif %}
        <div class="col">
            <h2>{{ doc.title }}</h2>
            <p>Текст: {{ doc.content }} {{ doc.content }}</p>
            <p class="font-italic"> Приоритет: {{ doc.priority }}</p>
            <p class="text-right font-italic">Документ распознан {{ doc.published }}</p>
        </div>
    </div>
</div>
<p><a href="{% url 'main:profile' %}">Назад</a></p>
{% endblock %}

main/templates/main/register_done.html
{% extends "layout/basic.html" %}

{% block title %}Регистрация завершена{% endblock %}

{% block content %}
<h2>Регистрация</h2>
<p>Регистрация пользователя завершена.</p>
{% endblock %}

main/templates/main/register_user.html
{% extends "layout/basic.html" %}

{% load bootstrap4 %}

{% block title %}Регистрация{% endblock %}

{% block content %}
<h2>Регистрация нового пользователя</h2>
<form method="post">
    {% csrf_token %}
    {% bootstrap_form form layout='horizontal' %}
    {% buttons submit='Зарегистрироваться' %}{% endbuttons %}
</form>
{% endblock %}